import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "it" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  it: {
    // Navbar
    "nav.home": "Home",
    "nav.services": "Servizi",
    "nav.about": "Chi Siamo",
    "nav.expertise": "Competenze",
    "nav.contracts": "Contratti",
    "nav.pricing": "Consulenze",
    "nav.contact": "Contattaci",
    "nav.logout": "Esci",

    // Hero Section
    "hero.partner": "IL TUO PARTNER",
    "hero.with": "CON",
    "hero.word1": "REATTIVITÀ.",
    "hero.word2": "COMPETENZA.",
    "hero.word3": "AFFIDABILITÀ.",
    "hero.description": "Coniughiamo la reattività di un team legale interno con la preparazione di uno studio di livello internazionale. La vostra crescita è la nostra missione.",
    "hero.cta": "Richiedi Consulenza",
    "hero.italy": "Italia",
    "hero.cyprus": "Cipro",
    "hero.clients": "Clienti assistiti con successo",
    "hero.international": "Presenza Internazionale",
    "hero.outsourcing": "Studio Legale in OutSourcing",
    "hero.support": "Supporto continuo",
    "hero.costs": "Costi sostenibili",

    // Legal Categories Marquee
    "marquee.generalCounselling": "General Counselling",
    "marquee.internationalTrade": "Commercio Internazionale",
    "marquee.maCorporate": "M&A & Societario",
    "marquee.contracts": "Contrattualistica",
    "marquee.compliance": "Compliance & GDPR",
    "marquee.businessDev": "Business Development",
    "marquee.civilLaw": "Diritto Civile",
    "marquee.laborLaw": "Diritto del Lavoro",
    "marquee.bankingLaw": "Diritto Bancario",
    "marquee.litigation": "Contenzioso",

    // Case Types Section
    "services.badge": "I Nostri Servizi",
    "services.title": "Soluzioni legali per ogni esigenza",
    "services.description": "Offriamo servizi strutturati per accompagnare PMI e grandi imprese in ogni sfida legale, con costi sostenibili e qualità internazionale.",
    "services.scrollHint": "Scorri per vedere tutti i servizi",
    "services.requestConsultation": "Richiedi consulenza",
    "services.consulting": "Consulenza",
    "services.international": "Internazionale",
    "services.corporate": "Societario",
    "services.complianceTag": "Compliance",
    "services.dailySupport": "Supporto quotidiano",
    "services.globalExpansion": "Espansione globale",
    "services.extraordinaryOps": "Operazioni straordinarie",
    "services.guaranteedCompliance": "Conformità garantita",
    "services.continuousLegal": "Assistenza legale continuativa",
    "services.quickResponse": "Risposta rapida",
    "services.dedicatedTeam": "Team dedicato",
    "services.internationalContracts": "Contratti internazionali",
    "services.customsRegulations": "Normativa doganale",
    "services.foreignRelations": "Rapporti esteri",
    "services.dueDiligence": "Due diligence",
    "services.mergersAcquisitions": "Fusioni e acquisizioni",
    "services.restructuring": "Ristrutturazioni",
    "services.privacyGdpr": "Privacy & GDPR",
    "services.dlgs231": "D.Lgs 231/2001",
    "services.complianceAudit": "Audit compliance",
    "services.contractsTag": "Contratti",
    "services.secureAgreements": "Accordi sicuri",
    "services.draftingNegotiation": "Redazione e negoziazione",
    "services.contractReview": "Revisione contratti",
    "services.contractManagement": "Gestione contrattuale",
    "services.litigationTag": "Contenzioso",
    "services.defenseProtection": "Difesa e tutela",
    "services.civilLitigation": "Contenzioso civile",
    "services.commercialDisputes": "Controversie commerciali",
    "services.alternativeResolution": "Risoluzione alternativa",
    "services.whyUs": "Perché affidarti a noi?",
    "services.whatWeOffer": "Cosa offriamo",
    "services.requestQuote": "Richiedi Preventivo",
    "services.learnMore": "Scopri di più",
    "services.clickForDetails": "Clicca per dettagli",

    // How It Works
    "how.badge": "Come Lavoriamo",
    "how.title1": "Dal primo contatto",
    "how.title2": "alla partnership",
    "how.description": "Un processo chiaro e trasparente per costruire un rapporto di fiducia duraturo.",
    "how.step1.title": "Primo contatto",
    "how.step1.description": "Ci racconti la tua situazione e le tue esigenze. Ascoltiamo attentamente per capire come possiamo aiutarti al meglio.",
    "how.step2.title": "Analisi e strategia",
    "how.step2.description": "Il nostro team analizza il caso e definisce la strategia più efficace, con la reattività di uno studio interno e la competenza internazionale.",
    "how.step3.title": "Proposta personalizzata",
    "how.step3.description": "Presentiamo una proposta chiara con costi definiti e tempi certi. Trasparenza totale, senza sorprese.",
    "how.step4.title": "Partnership duratura",
    "how.step4.description": "Costruiamo un rapporto di fiducia nel tempo, diventando il vostro partner strategico per ogni sfida legale.",
    "how.quote": "\"Questa legal boutique è nata dalla mia passione verso il mondo delle imprese e della professione. Provvediamo ad offrire i nostri servizi ogni giorno con piena soddisfazione e senza inutili complicazioni.\"",
    "how.quoteAuthor": "— Barbara Zogno, Founder e Managing Partner",
    "how.cta": "Richiedi una Consulenza",

    // Features Section
    "features.whyUs": "Perché affidarti a noi?",
    "features.whyChoose": "Perché le imprese ci scelgono",
    "features.learnMore": "Scopri di più",
    "features.requestConsultation": "Richiedi Consulenza",
    "features.badge": "Le Nostre Competenze",
    "features.title": "Expertise che fa la differenza",
    "features.description": "Competenze specialistiche sviluppate in anni di esperienza al fianco delle imprese.",

    // Pricing Section
    "pricing.badge": "Consulenze Legali",
    "pricing.title1": "Consulenze con",
    "pricing.title2": "pagamento anticipato",
    "pricing.description": "Scegli la consulenza più adatta alle tue esigenze. Pagamento sicuro online, servizio garantito.",
    "pricing.mostRequested": "Più Richiesto",
    "pricing.singleConsultations": "Consulenze Singole",
    "pricing.prepaidPackages": "Pacchetti Ore Prepagati",
    "pricing.buyNow": "Acquista ora",
    "pricing.contactInfoTitle": "I tuoi dati di contatto",
    "pricing.yourName": "Nome e Cognome",
    "pricing.namePlaceholder": "Mario Rossi",
    "pricing.proceedToPayment": "Procedi al pagamento",
    "pricing.quickCall": "Quick Legal Call",
    "pricing.quickCallDesc": "Chiamata legale rapida per questioni urgenti",
    "pricing.standard": "Consulenza Standard",
    "pricing.standardDesc": "Consulenza approfondita con follow-up scritto",
    "pricing.base": "Pacchetto Base",
    "pricing.baseDesc": "Per esigenze ricorrenti di supporto legale",
    "pricing.growth": "Pacchetto Growth",
    "pricing.growthDesc": "Ideale per PMI in crescita",
    "pricing.strategic": "Pacchetto Strategic",
    "pricing.strategicDesc": "Per imprese con esigenze legali complesse",
    "pricing.duration30min": "30 minuti",
    "pricing.duration1h": "1 ora",
    "pricing.duration2h": "2 ore",
    "pricing.duration5h": "5 ore",
    "pricing.duration10h": "10 ore",
    "pricing.includesFollowUp": "Include follow-up",
    "pricing.feat.phoneConsultation": "Consulenza telefonica dedicata",
    "pricing.feat.quickAnalysis": "Analisi rapida del caso",
    "pricing.feat.actionableAdvice": "Indicazioni operative immediate",
    "pricing.feat.deepAnalysis": "Analisi approfondita",
    "pricing.feat.writtenFollowUp": "Follow-up scritto incluso",
    "pricing.feat.actionPlan": "Piano d'azione personalizzato",
    "pricing.feat.documentReview": "Revisione documentale",
    "pricing.feat.flexibleUsage": "Utilizzo flessibile nel tempo",
    "pricing.feat.priorityAccess": "Accesso prioritario",
    "pricing.feat.writtenSummary": "Riepilogo scritto di ogni sessione",
    "pricing.feat.dedicatedLawyer": "Avvocato dedicato",
    "pricing.feat.monthlyReport": "Report mensile attività",
    "pricing.feat.strategicPlanning": "Pianificazione strategica legale",
    "pricing.included": "Cosa è incluso",
    "pricing.notIncluded": "Non incluso",
    "pricing.incl.analysis": "Analisi preliminare del caso",
    "pricing.incl.oralAdvice": "Consulenza orale specializzata",
    "pricing.incl.writtenFollowUp": "Follow-up scritto (Consulenza Standard e Pacchetti)",
    "pricing.incl.simpleDocReview": "Revisione documentale semplice",
    "pricing.incl.strategy": "Indicazioni strategiche e operative",
    "pricing.excl.draftingContracts": "Redazione contratti e documenti complessi",
    "pricing.excl.courtFiling": "Deposito atti giudiziali",
    "pricing.excl.notarization": "Autenticazioni notarili",
    "pricing.excl.adminFees": "Spese amministrative e bolli",
    "pricing.trustText": "🔒 Pagamento sicuro · ⚖️ Servizio garantito · 🌍 Disponibilità internazionale",
    "pricing.termsTitle": "Condizioni di vendita",
    "pricing.term.prepayment": "Il pagamento è richiesto in anticipo prima dell'erogazione del servizio.",
    "pricing.term.validity": "I pacchetti ore hanno validità 6 mesi dalla data di acquisto.",
    "pricing.term.scheduling": "Le consulenze vengono erogate previo appuntamento concordato.",
    "pricing.term.cancellation": "Cancellazione gratuita fino a 24 ore prima dell'appuntamento.",
    "pricing.term.nonTransferable": "I pacchetti sono personali e non cedibili a terzi.",
    "pricing.term.noRefund": "Non sono previsti rimborsi per le ore non utilizzate alla scadenza del pacchetto.",

    // Contract Templates Section
    "contracts.badge": "Modelli Pronti all'Uso",
    "contracts.title1": "Contratti Professionali",
    "contracts.title2": "a portata di click",
    "contracts.description": "Modelli di contratto redatti dai nostri avvocati, pronti per essere personalizzati. Risparmia tempo e denaro con documenti legali professionali.",
    "contracts.draftedByLawyers": "Redatti da avvocati",
    "contracts.immediateDownload": "Download immediato",
    "contracts.updated": "Aggiornati 2024",
    "contracts.scrollHint": "Scorri per vedere tutti i contratti",
    "contracts.customRequest": "Hai bisogno di un contratto su misura? Contattaci per una consulenza personalizzata.",
    "contracts.requestCustom": "Richiedi contratto personalizzato",
    "contracts.mostSold": "Più venduto",
    "contracts.buyNow": "Acquista ora",

    // Footer
    "footer.ctaTitle": "Pronti a diventare il vostro partner legale?",
    "footer.ctaDescription": "Contattateci per una consulenza gratuita. Costruiamo insieme il futuro della vostra impresa.",
    "footer.requestConsultation": "Richiedi Consulenza",
    "footer.callUs": "Chiamaci",
    "footer.services": "Servizi",
    "footer.studio": "Studio",
    "footer.legal": "Legale",
    "footer.aboutUs": "Chi Siamo",
    "footer.team": "Il Team",
    "footer.contact": "Contatti",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.cookiePolicy": "Cookie Policy",
    "footer.description": "Legal Boutique con la reattività di un team interno e la competenza di uno studio internazionale.",
    "footer.allRights": "Tutti i diritti riservati.",
    "footer.developedWith": "Sviluppato con",
    "footer.by": "da",
    "footer.lawyerAccess": "Area Avvocati",

    // Contact Form
    "contact.badge": "Contattaci",
    "contact.title": "Richiedi una consulenza",
    "contact.description": "Compila il form e ti ricontatteremo entro 24 ore per discutere le tue esigenze legali.",
    "contact.firstName": "Nome",
    "contact.firstNamePlaceholder": "Mario",
    "contact.lastName": "Cognome",
    "contact.lastNamePlaceholder": "Rossi",
    "contact.reason": "Motivo della consulenza",
    "contact.reasonPlaceholder": "Descrivi brevemente il motivo della consulenza...",
    "contact.sendWhatsapp": "Invia su WhatsApp",
    "contact.privacy": "Inviando il form accetti la nostra Privacy Policy",
    "contact.whatsappHeader": "Richiesta Consulenza",
    "contact.whatsappName": "Nome",
    "contact.whatsappReason": "Motivo della consulenza",
  },
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.about": "About Us",
    "nav.expertise": "Expertise",
    "nav.contracts": "Contracts",
    "nav.pricing": "Consultations",
    "nav.contact": "Contact Us",
    "nav.logout": "Logout",

    // Hero Section
    "hero.partner": "YOUR PARTNER",
    "hero.with": "WITH",
    "hero.word1": "REACTIVITY.",
    "hero.word2": "EXPERTISE.",
    "hero.word3": "RELIABILITY.",
    "hero.description": "We combine the reactivity of an in-house legal team with the expertise of an international law firm. Your growth is our mission.",
    "hero.cta": "Request Consultation",
    "hero.italy": "Italy",
    "hero.cyprus": "Cyprus",
    "hero.clients": "Clients successfully assisted",
    "hero.international": "International Presence",
    "hero.outsourcing": "Outsourced Legal Services",
    "hero.support": "Continuous support",
    "hero.costs": "Sustainable costs",

    // Legal Categories Marquee
    "marquee.generalCounselling": "General Counselling",
    "marquee.internationalTrade": "International Trade",
    "marquee.maCorporate": "M&A & Corporate",
    "marquee.contracts": "Contract Law",
    "marquee.compliance": "Compliance & GDPR",
    "marquee.businessDev": "Business Development",
    "marquee.civilLaw": "Civil Law",
    "marquee.laborLaw": "Labor Law",
    "marquee.bankingLaw": "Banking Law",
    "marquee.litigation": "Litigation",

    // Case Types Section
    "services.badge": "Our Services",
    "services.title": "Legal solutions for every need",
    "services.description": "We offer structured services to support SMEs and large companies in every legal challenge, with sustainable costs and international quality.",
    "services.scrollHint": "Scroll to see all services",
    "services.requestConsultation": "Request consultation",
    "services.consulting": "Consulting",
    "services.international": "International",
    "services.corporate": "Corporate",
    "services.complianceTag": "Compliance",
    "services.dailySupport": "Daily support",
    "services.globalExpansion": "Global expansion",
    "services.extraordinaryOps": "Extraordinary operations",
    "services.guaranteedCompliance": "Guaranteed compliance",
    "services.continuousLegal": "Continuous legal assistance",
    "services.quickResponse": "Quick response",
    "services.dedicatedTeam": "Dedicated team",
    "services.internationalContracts": "International contracts",
    "services.customsRegulations": "Customs regulations",
    "services.foreignRelations": "Foreign relations",
    "services.dueDiligence": "Due diligence",
    "services.mergersAcquisitions": "Mergers & acquisitions",
    "services.restructuring": "Restructuring",
    "services.privacyGdpr": "Privacy & GDPR",
    "services.dlgs231": "D.Lgs 231/2001",
    "services.complianceAudit": "Compliance audit",
    "services.contractsTag": "Contracts",
    "services.secureAgreements": "Secure agreements",
    "services.draftingNegotiation": "Drafting & negotiation",
    "services.contractReview": "Contract review",
    "services.contractManagement": "Contract management",
    "services.litigationTag": "Litigation",
    "services.defenseProtection": "Defense & protection",
    "services.civilLitigation": "Civil litigation",
    "services.commercialDisputes": "Commercial disputes",
    "services.alternativeResolution": "Alternative resolution",
    "services.whyUs": "Why trust us?",
    "services.whatWeOffer": "What we offer",
    "services.requestQuote": "Request Quote",
    "services.learnMore": "Learn more",
    "services.clickForDetails": "Click for details",

    // How It Works
    "how.badge": "How We Work",
    "how.title1": "From first contact",
    "how.title2": "to partnership",
    "how.description": "A clear and transparent process to build a lasting relationship of trust.",
    "how.step1.title": "First contact",
    "how.step1.description": "Tell us about your situation and needs. We listen carefully to understand how we can best help you.",
    "how.step2.title": "Analysis and strategy",
    "how.step2.description": "Our team analyzes the case and defines the most effective strategy, with the reactivity of an in-house firm and international expertise.",
    "how.step3.title": "Customized proposal",
    "how.step3.description": "We present a clear proposal with defined costs and certain timelines. Total transparency, no surprises.",
    "how.step4.title": "Lasting partnership",
    "how.step4.description": "We build a relationship of trust over time, becoming your strategic partner for every legal challenge.",
    "how.quote": "\"This legal boutique was born from my passion for the business world and the profession. We provide our services every day with full satisfaction and without unnecessary complications.\"",
    "how.quoteAuthor": "— Barbara Zogno, Founder and Managing Partner",
    "how.cta": "Request a Consultation",

    // Features Section
    "features.whyUs": "Why trust us?",
    "features.whyChoose": "Why companies choose us",
    "features.learnMore": "Learn more",
    "features.requestConsultation": "Request Consultation",
    "features.badge": "Our Expertise",
    "features.title": "Expertise that makes the difference",
    "features.description": "Specialized skills developed through years of experience alongside companies.",

    // Pricing Section
    "pricing.badge": "Legal Consultations",
    "pricing.title1": "Consultations with",
    "pricing.title2": "upfront payment",
    "pricing.description": "Choose the consultation that best fits your needs. Secure online payment, guaranteed service.",
    "pricing.mostRequested": "Most Requested",
    "pricing.singleConsultations": "Single Consultations",
    "pricing.prepaidPackages": "Prepaid Hour Packages",
    "pricing.buyNow": "Buy now",
    "pricing.contactInfoTitle": "Your contact info",
    "pricing.yourName": "Full Name",
    "pricing.namePlaceholder": "John Smith",
    "pricing.proceedToPayment": "Proceed to payment",
    "pricing.quickCall": "Quick Legal Call",
    "pricing.quickCallDesc": "Quick legal call for urgent matters",
    "pricing.standard": "Standard Consultation",
    "pricing.standardDesc": "In-depth consultation with written follow-up",
    "pricing.base": "Base Package",
    "pricing.baseDesc": "For recurring legal support needs",
    "pricing.growth": "Growth Package",
    "pricing.growthDesc": "Ideal for growing SMEs",
    "pricing.strategic": "Strategic Package",
    "pricing.strategicDesc": "For companies with complex legal needs",
    "pricing.duration30min": "30 minutes",
    "pricing.duration1h": "1 hour",
    "pricing.duration2h": "2 hours",
    "pricing.duration5h": "5 hours",
    "pricing.duration10h": "10 hours",
    "pricing.includesFollowUp": "Includes follow-up",
    "pricing.feat.phoneConsultation": "Dedicated phone consultation",
    "pricing.feat.quickAnalysis": "Quick case analysis",
    "pricing.feat.actionableAdvice": "Immediate actionable advice",
    "pricing.feat.deepAnalysis": "In-depth analysis",
    "pricing.feat.writtenFollowUp": "Written follow-up included",
    "pricing.feat.actionPlan": "Personalized action plan",
    "pricing.feat.documentReview": "Document review",
    "pricing.feat.flexibleUsage": "Flexible usage over time",
    "pricing.feat.priorityAccess": "Priority access",
    "pricing.feat.writtenSummary": "Written summary for each session",
    "pricing.feat.dedicatedLawyer": "Dedicated lawyer",
    "pricing.feat.monthlyReport": "Monthly activity report",
    "pricing.feat.strategicPlanning": "Legal strategic planning",
    "pricing.included": "What's included",
    "pricing.notIncluded": "Not included",
    "pricing.incl.analysis": "Preliminary case analysis",
    "pricing.incl.oralAdvice": "Specialized oral advice",
    "pricing.incl.writtenFollowUp": "Written follow-up (Standard & Packages)",
    "pricing.incl.simpleDocReview": "Simple document review",
    "pricing.incl.strategy": "Strategic and operational guidance",
    "pricing.excl.draftingContracts": "Drafting contracts and complex documents",
    "pricing.excl.courtFiling": "Court filing",
    "pricing.excl.notarization": "Notarization",
    "pricing.excl.adminFees": "Administrative fees and stamps",
    "pricing.trustText": "🔒 Secure payment · ⚖️ Guaranteed service · 🌍 International availability",
    "pricing.termsTitle": "Terms of sale",
    "pricing.term.prepayment": "Payment is required in advance before the service is provided.",
    "pricing.term.validity": "Hour packages are valid for 6 months from the date of purchase.",
    "pricing.term.scheduling": "Consultations are provided by prior appointment.",
    "pricing.term.cancellation": "Free cancellation up to 24 hours before the appointment.",
    "pricing.term.nonTransferable": "Packages are personal and non-transferable.",
    "pricing.term.noRefund": "No refunds for unused hours upon package expiration.",

    // Contract Templates Section
    "contracts.badge": "Ready-to-Use Templates",
    "contracts.title1": "Professional Contracts",
    "contracts.title2": "at your fingertips",
    "contracts.description": "Contract templates drafted by our lawyers, ready to be customized. Save time and money with professional legal documents.",
    "contracts.draftedByLawyers": "Drafted by lawyers",
    "contracts.immediateDownload": "Immediate download",
    "contracts.updated": "Updated 2024",
    "contracts.scrollHint": "Scroll to see all contracts",
    "contracts.customRequest": "Need a custom contract? Contact us for a personalized consultation.",
    "contracts.requestCustom": "Request custom contract",
    "contracts.mostSold": "Best seller",
    "contracts.buyNow": "Buy now",

    // Footer
    "footer.ctaTitle": "Ready to become your legal partner?",
    "footer.ctaDescription": "Contact us for a free consultation. Let's build the future of your company together.",
    "footer.requestConsultation": "Request Consultation",
    "footer.callUs": "Call Us",
    "footer.services": "Services",
    "footer.studio": "Firm",
    "footer.legal": "Legal",
    "footer.aboutUs": "About Us",
    "footer.team": "The Team",
    "footer.contact": "Contact",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.cookiePolicy": "Cookie Policy",
    "footer.description": "Legal Boutique with the reactivity of an in-house team and the expertise of an international firm.",
    "footer.allRights": "All rights reserved.",
    "footer.developedWith": "Developed with",
    "footer.by": "by",
    "footer.lawyerAccess": "Lawyer Access",

    // Contact Form
    "contact.badge": "Contact Us",
    "contact.title": "Request a consultation",
    "contact.description": "Fill out the form and we'll contact you within 24 hours to discuss your legal needs.",
    "contact.firstName": "First Name",
    "contact.firstNamePlaceholder": "John",
    "contact.lastName": "Last Name",
    "contact.lastNamePlaceholder": "Smith",
    "contact.reason": "Reason for consultation",
    "contact.reasonPlaceholder": "Briefly describe the reason for the consultation...",
    "contact.sendWhatsapp": "Send via WhatsApp",
    "contact.privacy": "By submitting the form you accept our Privacy Policy",
    "contact.whatsappHeader": "Consultation Request",
    "contact.whatsappName": "Name",
    "contact.whatsappReason": "Reason for consultation",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language");
      return (saved as Language) || "it";
    }
    return "it";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
