// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blseblymafrjfhheuiyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsc2VibHltYWZyamZoaGV1aXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0MDY5MTAsImV4cCI6MjA4Njk4MjkxMH0.2Ck8K580P9SMgDIeBzrfJlHQrK736ttoUwrHo6IfKeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});