// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://josgdhbscmchrfiwlfnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvc2dkaGJzY21jaHJmaXdsZm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxODQ2NjQsImV4cCI6MjA4NDc2MDY2NH0.8klvtaK_wIwQi3dacymfNvUUjfRjwA9wSw-3qhzbGpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});